### PR TITLE
note about Variant ID possibly changing

### PR DESCRIPTION
**Pull request by dnl**

### CODE REVIEW

**Comment by radar** [comment]
What is the context of this change?

**Comment by dnl** [comment]
https://marketplacer.atlassian.net/browse/PD-1228

**Comment by radar** [comment]
Can we have the comment at the top of the file, and then in the sections where it's reproduced, just point to the one comment? That'll make it easier if we need to update the comment in the future.

**Comment by dnl** [comment]
good to merge?

**Comment by radar** [comment]
LGTM

**Pull request merged**
